-- CREATE TABLE users (
-- id SERIAL PRIMARY KEY,
-- first_name Varchar(20),
-- last_name Varchar(20),
-- email Varchar(60),
-- profile_img Text, 
-- phone Varchar(15)
-- )

-- CREATE TABLE connections (
-- id SERIAL PRIMARY KEY,
-- requester_id INTEGER,
-- requestee_id INTEGER,
-- is_active BOOLEAN,
-- status Varchar(20) (sent, accepted,inactive)
-- )

-- CREATE TABLE posts(
-- id SERIAL PRIMARY KEY,
-- user_id INTEGER,
-- text_content TEXT,
-- img TEXT,
-- created_at INTEGER
-- )